mujoco:
  add_odom_joints: true
  
  spawn_and_destroy_objects_rate: 0.0

  root_frame_id: map

multiverse:
  length_unit: m
  angle_unit: rad
  force_unit: N
  time_unit: s
  handedness: rhs
  root_frame_id: map
  
  send:
    body: [position, quaternion]
    joint: [joint_rvalue, joint_tvalue]