mujoco:
  joint_inits:
    shoulder_pan_joint: 1
    shoulder_lift_joint: -1
    elbow_joint: -1
    wrist_1_joint: -1
    wrist_2_joint: 1
    wrist_3_joint: 1

  spawn_and_destroy_objects_rate: 0.0

  root_frame_id: map

multiverse:
  send:
    ur5e: [position, quaternion, joint_rvalue, joint_tvalue]