joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 60

joint_trajectory_controller: 
  type: effort_controllers/JointTrajectoryController  
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 2000, i: 100, d: 50}
    shoulder_lift_joint: {p: 2000, i: 100, d: 50}
    elbow_joint: {p: 2000, i: 100, d: 50}
    wrist_1_joint: {p: 2000, i: 100, d: 50}
    wrist_2_joint: {p: 2000, i: 100, d: 50}
    wrist_3_joint: {p: 2000, i: 100, d: 50}
  constraints:
    goal_time: 0.5
    shoulder_pan_joint: { goal: 0.05 }
    shoulder_lift_joint: { goal: 0.05 }
    elbow_joint: { goal: 0.05 }
    wrist_1_joint: { goal: 0.05 }
    wrist_2_joint: { goal: 0.05 }
    wrist_3_joint: { goal: 0.05 }

gripper_controller:
  type: effort_controllers/GripperActionController
  joint: gripper_hand_e_finger_1_joint
  gains:
    gripper_hand_e_finger_1_joint: { p: 2000, i: 100, d: 50 }